### ISSUE TITLE
It should be possible for a file system not to implement all operations

### ISSUE THREAD

**Issue by billziss-gh** [yogendersolanki91/winfsp#12]
Currently it seems to be required that all operations in `WinFspMinimalOperation` must be implemented for example.

It is best not to set any callback for unimplemented operations and the WinFsp DLL will handle it on its own.

**Comment by yogendersolanki91** [comment]
> It is best not to set any callback for unimplemented operations and the WinFsp DLL will handle it on its own.


I could not found best way to identify which function actually implemented. If a class implementing an interface it will implement all the function.

**Comment by yogendersolanki91** [comment]
Best way of doing is use of delegate function. I am not sure about the performance or frankly saying i was little bit skeptical about delegate performance.  I am going to replace them with delegates. What do you say @billziss-gh .

**Comment by billziss-gh** [comment]
We also need to keep in mind that more file system operations may be added to `FSP_FILE_SYSTEM_INTERFACE`. It is not clear to me whether one is allowed to add operations to an .NET `interface` once it has been published.

The delegate mechanism sounds like a good solution (caveat: as I have mentioned my C#/.NET knowledge is rusty).

Another solution might be to provide a base class (e.g. `FileSystem` or `BaseFileSystem` or similar) that implements stubs for all file system operations by returning `STATUS_INVALID_DEVICE_REQUEST` and then allow the actual file system implementations to implement the operations they need.

**Comment by yogendersolanki91** [comment]
> We also need to keep in mind that more file system operations may be added to FSP_FILE_SYSTEM_INTERFACE. It is not clear to me whether one is allowed to add operations to an .NET interface once it has been published.

.NET interface doesn't allow this. We can add versioning to interface FileSystemInteface. e.g. FileSystemInterfaceV2 it is derived from FileSystemInteface it will allow us to add more operation without breaking application which are using WinFsp. As u mentioned earlier it will required only if major version is changed. 

> Another solution might be to provide a base class (e.g. FileSystem or BaseFileSystem or similar) that implements stubs for all file system operations by returning STATUS_INVALID_DEVICE_REQUEST and then allow the actual file system implementations to implement the operations they need.

Yes this can be done using abstract class implementation in C++/CLI.
