### ISSUE TITLE
Discussion: common interface for native C++ and .NET

### ISSUE THREAD

**Issue by billziss-gh** [yogendersolanki91/winfsp#18]
I wanted to discuss the idea of having a more or less common interface between **native** C++ and .NET.

For example, imagine that we expose for the native C++ an interface that looks like this:

```c++
class FileSystem
{
public:
    FileSystem(/*...*/);
    virtual NTSTATUS GetSecurityByName(/*...*/);
    virtual NTSTATUS Create(/*...*/);
// ...
};
```

In .NET we expose a very similar interface (I am actually not well versed in C++/CLI):

```c++
public ref class FileSystem
{
public:
    FileSystem(/*... same args as native to the extent that is possible */);
    virtual NTSTATUS GetSecurityByName(/*...*/);
    virtual NTSTATUS Create(/*...*/);
}
```

It might even be possible to support both interfaces (native C++ and .NET) from the same code.

[NOTE: this is just an idea for discussion and it may in fact be an exceptionally bad idea.]

**Comment by billziss-gh** [comment]
Here is my initial implementation of a C++ (only) layer. Do you think we could/should follow a similar approach for the .NET layer?

https://github.com/billziss-gh/winfsp/blob/c%2B%2B/inc/winfsp/winfsp.hpp

[NOTE: This is currently in the c++ branch and it compiles, but has received **no** testing.]

**Comment by yogendersolanki91** [comment]
Looks good to me. I was planning for a similar approach but I was in hurry so I just rushed into writing the prototype wrapper. In next commit cleanup and fixup the interface the code so that it can align with this approach.

**Comment by yogendersolanki91** [comment]
Just committed initial version for interface. I would like to know you view on this before proceeding further.

**Comment by billziss-gh** [comment]
Just pulled the code and will look at it shortly.

**Comment by billziss-gh** [comment]
I looked at your new code and I think we are headed in the right direction. Thank you.

- I particularly like that you are now using `GCHandle` through nice and tidy macros `HANDLE_TO_FILESYSTEM` and `HANDLE_TO_FILECONTEXT`. Makes the code in `WinFspCallbacks` easy to understand.

- IMO it would look better and cleaner if we simply merged `FileSystem` and `FileSystemInterface`, i.e. if we placed all virtual methods in `FileSystemInterface` under `FileSystem` and required that file system implementations inherit from `FileSystem` rather than `FileSystemInterface`.

- Similarly it might make things simpler if `WinFspCallbacks` and `FileSystem` were merged. The reason is that `WinFspCallbacks` is really an implementation detail of `FileSystem`. [Perhaps there is a good reason that this cannot or should not be done in C++/CLI, please let me know if this is the case.]

- I will look into the specifics of how marshaling is done for `FileInfo`, `VolumeInfo`, `SecurityDescriptor`, etc. and may come back with more comments.

---

**EDIT**: some additional comments:

- `COPY_FILE_INFO` appears to unnecessarily allocate and copy memory. Would it not work if it was simply:

        #define COPY_FILE_INFO(fInfo,PtrInfo) Marshal::StructureToPtr(fInfo, IntPtr::IntPtr(PtrInfo), false)

- For security descriptors we should probably be using `System.Security.AccessControl.GenericSecurityDescriptor` and its subclasses.

- For `NTSTATUS`: the file `src/sys/ntstatus.i` contains all `STATUS_*` values and is used by the FSD. With a bit of Cygwin sed we can create a similar `src/dotnet/ntstatus.i` file that is included from within the `FileSystem` class and contains definitions like:

        static const NTSTATUS STATUS_OBJECT_NAME_NOT_FOUND = ((NTSTATUS)0xC0000034L);

**Comment by billziss-gh** [comment]
BTW, I have updated the C++ layer and I am now testing it with a simple `passthrough-cpp` file system.

There is a `Fsp::Service` class in there too, but I do not believe we need to port this to .NET, as .NET has its own mechanism for creating Windows services.

**Comment by billziss-gh** [comment]
I have created an [`ntstatus.i`](https://gist.github.com/billziss-gh/9a98ac78d788f874a6152a387735a0fc#file-ntstatus-i) file that contains `STATUS_*` symbol definitions. You can use by copying into `src/dotnet` and including from within the `FileSystem` class as follows:

```c++
public ref class FileSystem {

...

public:
    #include "ntstatus.i"

...

};
```

I used this [C program](https://gist.github.com/billziss-gh/9a98ac78d788f874a6152a387735a0fc#file-p-c) to create the `ntstatus.i` file.

**Comment by yogendersolanki91** [comment]
This sounds cool. have you checked for any compilation issues?

**Comment by billziss-gh** [comment]
> This sounds cool. have you checked for any compilation issues?

If you are talking about `ntstatus.i` it compiles fine for me.

**Comment by yogendersolanki91** [comment]
Ok I am adding this to my code. Thanks for suggestion.
