### ISSUE TITLE
Remove .gitattributes and .gitignore files

### ISSUE THREAD

**Issue by billziss-gh** [yogendersolanki91/winfsp#2]
These files in the root directory of the fork appear unnecessary. Furthermore they cause various issues with line endings (CRLF vs LF) on files.

Various files (e.g. vcxproj files) appear modified, but upon further examination it is only line endings that have been changed. I suspect that the .gitattributes file and the `* text=auto` line may be responsible.

**Comment by yogendersolanki91** [comment]
Done
