### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by billziss-gh** [yogendersolanki91/winfsp#5]
We would probably have to reformat files as to conform with the coding style of the rest of WinFsp.

In the related issue of whitespace, source files in WinFsp use UNIX line endings (LF) and no tabs. Indentation style is 4 spaces. Exceptions: some files (e.g. batch files) must use Windows line endings (CRLF); other files (e.g. make files) must use tabs.

**Comment by yogendersolanki91** [comment]
Done.
